package ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * DBupdateService service = new DBupdateService();
 * DBupdate portType = service.getDBupdate();
 * portType.outboundUpdateMainOrder(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "DBupdateService", targetNamespace = "http://ws", wsdlLocation = "http://192.168.1.128/GuobangWebservice/services/DBupdate?wsdl")
public class DBupdateService extends Service {

	private final static URL DBUPDATESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(ws.DBupdateService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = ws.DBupdateService.class.getResource(".");
			url = new URL(baseUrl,
					"http://192.168.1.128/GuobangWebservice/services/DBupdate?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.1.128/GuobangWebservice/services/DBupdate?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		DBUPDATESERVICE_WSDL_LOCATION = url;
	}

	public DBupdateService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public DBupdateService() {
		super(DBUPDATESERVICE_WSDL_LOCATION, new QName("http://ws",
				"DBupdateService"));
	}

	/**
	 * 
	 * @return returns DBupdate
	 */
	@WebEndpoint(name = "DBupdate")
	public DBupdate getDBupdate() {
		return super
				.getPort(new QName("http://ws", "DBupdate"), DBupdate.class);
	}

}
