package ws;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "DBupdate", targetNamespace = "http://ws")
public interface DBupdate {

	/**
	 * 
	 * @param cCode
	 * @param index
	 * @param cDepName
	 * @param dDate
	 * @param cBusType
	 * @param cVenName
	 * @param cMemo
	 * @return returns int
	 */
	@WebMethod
	@WebResult(name = "outboundUpdateMainOrderReturn", targetNamespace = "http://ws")
	@RequestWrapper(localName = "outboundUpdateMainOrder", targetNamespace = "http://ws", className = "ws.OutboundUpdateMainOrder")
	@ResponseWrapper(localName = "outboundUpdateMainOrderResponse", targetNamespace = "http://ws", className = "ws.OutboundUpdateMainOrderResponse")
	public int outboundUpdateMainOrder(
			@WebParam(name = "index", targetNamespace = "http://ws") int index,
			@WebParam(name = "cCode", targetNamespace = "http://ws") String cCode,
			@WebParam(name = "dDate", targetNamespace = "http://ws") String dDate,
			@WebParam(name = "cBusType", targetNamespace = "http://ws") String cBusType,
			@WebParam(name = "cVenName", targetNamespace = "http://ws") String cVenName,
			@WebParam(name = "cMemo", targetNamespace = "http://ws") String cMemo,
			@WebParam(name = "cDepName", targetNamespace = "http://ws") String cDepName);

	/**
	 * 
	 * @param cInvStd
	 * @param iUnitCost
	 * @param index
	 * @param bRdFlag
	 * @param iPrice
	 * @param dDate
	 * @param cBatch
	 * @param cInvName
	 * @param iQuantity
	 * @return returns int
	 */
	@WebMethod
	@WebResult(name = "outboundUpdateMainReturn", targetNamespace = "http://ws")
	@RequestWrapper(localName = "outboundUpdateMain", targetNamespace = "http://ws", className = "ws.OutboundUpdateMain")
	@ResponseWrapper(localName = "outboundUpdateMainResponse", targetNamespace = "http://ws", className = "ws.OutboundUpdateMainResponse")
	public int outboundUpdateMain(
			@WebParam(name = "index", targetNamespace = "http://ws") int index,
			@WebParam(name = "bRdFlag", targetNamespace = "http://ws") int bRdFlag,
			@WebParam(name = "dDate", targetNamespace = "http://ws") String dDate,
			@WebParam(name = "cBatch", targetNamespace = "http://ws") String cBatch,
			@WebParam(name = "cInvName", targetNamespace = "http://ws") String cInvName,
			@WebParam(name = "iQuantity", targetNamespace = "http://ws") double iQuantity,
			@WebParam(name = "cInvStd", targetNamespace = "http://ws") String cInvStd,
			@WebParam(name = "iPrice", targetNamespace = "http://ws") BigDecimal iPrice,
			@WebParam(name = "iUnitCost", targetNamespace = "http://ws") double iUnitCost);

	/**
	 * 
	 * @param index
	 * @return returns int
	 */
	@WebMethod
	@WebResult(name = "outboundDeleteMainReturn", targetNamespace = "http://ws")
	@RequestWrapper(localName = "outboundDeleteMain", targetNamespace = "http://ws", className = "ws.OutboundDeleteMain")
	@ResponseWrapper(localName = "outboundDeleteMainResponse", targetNamespace = "http://ws", className = "ws.OutboundDeleteMainResponse")
	public int outboundDeleteMain(
			@WebParam(name = "index", targetNamespace = "http://ws") int index);

	/**
	 * 
	 * @param cCode
	 * @param index
	 * @param bRdFlag
	 * @param dDate
	 * @param iPrice
	 * @param cBatch
	 * @param cBusType
	 * @param iQuantity
	 * @param cWhCode
	 * @param cInvStd
	 * @param iUnitCost
	 * @param cDepCode
	 * @param cMaker
	 * @param cInvName
	 * @return returns int
	 */
	@WebMethod
	@WebResult(name = "outboundInsertMainReturn", targetNamespace = "http://ws")
	@RequestWrapper(localName = "outboundInsertMain", targetNamespace = "http://ws", className = "ws.OutboundInsertMain")
	@ResponseWrapper(localName = "outboundInsertMainResponse", targetNamespace = "http://ws", className = "ws.OutboundInsertMainResponse")
	public int outboundInsertMain(
			@WebParam(name = "index", targetNamespace = "http://ws") int index,
			@WebParam(name = "bRdFlag", targetNamespace = "http://ws") int bRdFlag,
			@WebParam(name = "dDate", targetNamespace = "http://ws") String dDate,
			@WebParam(name = "cBatch", targetNamespace = "http://ws") String cBatch,
			@WebParam(name = "cInvName", targetNamespace = "http://ws") String cInvName,
			@WebParam(name = "cWhCode", targetNamespace = "http://ws") String cWhCode,
			@WebParam(name = "iQuantity", targetNamespace = "http://ws") double iQuantity,
			@WebParam(name = "cInvStd", targetNamespace = "http://ws") String cInvStd,
			@WebParam(name = "cCode", targetNamespace = "http://ws") String cCode,
			@WebParam(name = "cDepCode", targetNamespace = "http://ws") String cDepCode,
			@WebParam(name = "cBusType", targetNamespace = "http://ws") String cBusType,
			@WebParam(name = "cMaker", targetNamespace = "http://ws") String cMaker,
			@WebParam(name = "iPrice", targetNamespace = "http://ws") BigDecimal iPrice,
			@WebParam(name = "iUnitCost", targetNamespace = "http://ws") double iUnitCost);

	/**
	 * 
	 * @param canOutQuantity
	 * @param bRdFlag
	 * @param inAutoID
	 * @param iQuantity
	 * @return returns int
	 */
	@WebMethod
	@WebResult(name = "testReturn", targetNamespace = "http://ws")
	@RequestWrapper(localName = "test", targetNamespace = "http://ws", className = "ws.Test")
	@ResponseWrapper(localName = "testResponse", targetNamespace = "http://ws", className = "ws.TestResponse")
	public int test(
			@WebParam(name = "bRdFlag", targetNamespace = "http://ws") int bRdFlag,
			@WebParam(name = "iQuantity", targetNamespace = "http://ws") double iQuantity,
			@WebParam(name = "inAutoID", targetNamespace = "http://ws") int inAutoID,
			@WebParam(name = "canOutQuantity", targetNamespace = "http://ws") double canOutQuantity);

}
